# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache

# Theme skin + layout
minimal_mistakes_skin: default
breadcrumbs: true
search: true

# Author (left sidebar)
author:
  name: "Aman Patel"
  avatar: "/assets/images/headshot.jpeg"
  bio: "Computational Data Analytics @ Georgia Tech"
  location: "Atlanta, GA"
  links:
    - label: "aman0patel@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url : '#'
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AmanPatel117"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amanapatel/"

# Navigation
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults for pages and posts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      read_time: false
      share: false

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AmanPatel117"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amanapatel/"

